# Generated by Django 4.2 on 2023-04-27 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_rename_table_maintb_rename_result_resulttb"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="maintb",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="resulttb",
            options={"managed": False},
        ),
    ]
