# Generated by Django 4.2 on 2023-04-27 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_maintb_options_alter_resulttb_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="maintb",
            table="mainTB",
        ),
        migrations.AlterModelTable(
            name="resulttb",
            table="resultTB",
        ),
    ]
